### ISSUE TITLE
记一次家用空调接入HA折腾经历

### ISSUE THREAD

**Issue by mypal** [mypal/blog-comment#9]
https://www.mypal.wang/blog/p/5cad82a1-fda7-4369-b255-08623f7a5f67/

**Comment by mypal** [comment]
test

**Comment by zeruitle** [comment]
谢大佬。。。我这精装的大金中央空调，vrf都没有。。。就在找方案。。。
一遍是大金，另一边接HA，中间目前看到的几个方案是：
1. 淘宝不知道哪来的商家还有的DTA117D611+你的DS-AIR插件
2. 中弘B18SEH+HA官方中弘插件，官方客服说不支持接入HA
3. 绿米VRFKZQB19+homekit_controller，这款能接入米家，但官方客服也说不支持接入HA

抠脑壳。。。

**Comment by mypal** [comment]
> @zeruitle
> 谢大佬。。。我这精装的大金中央空调，vrf都没有。。。就在找方案。。。
> 一遍是大金，另一边接HA，中间目前看到的几个方案是：
> 1. 淘宝不知道哪来的商家还有的DTA117D611+你的DS-AIR插件
> 2. 中弘B18SEH+HA官方中弘插件，官方客服说不支持接入HA
> 3. 绿米VRFKZQB19+homekit_controller，这款能接入米家，但官方客服也说不支持接入HA
> 
> 抠脑壳。。。

DTA117D611根据群友反馈，用这插件没有问题的。官方客服估计不了解HA，肯定不敢答应。小米都是走MIOT协议的，能接入米家的肯定能接入ha，只不过米家的设备太多了，大部分插件都没有完整支持所有的设备，可能需要自己fork下插件，简单改改来支持。

**Comment by JiangNanGenius** [comment]
感谢大佬的插件解决了很大一部分问题包括自动风速，自动模式，请问大佬有没有兴趣把自动风向更新一下😂我尝试在IRACC网关下补足失败了，艾瑞科的文档看的太难受，估计我自己是无法搞定。

**Comment by linaariah** [comment]
大佬有没有机会后续开发把地暖模块的HD锅炉加入进去

**Comment by mypal** [comment]
> @linaariah
> 大佬有没有机会后续开发把地暖模块的HD锅炉加入进去

参考下这个，看看能不能用。我这没有地暖，测不了....
https://github.com/mypal/ha-dsair/issues/26

**Comment by zeruitle** [comment]
> > [@zeruitle](https://github.com/zeruitle)
> > 谢大佬。。。我这精装的大金中央空调，vrf都没有。。。就在找方案。。。
> > 一遍是大金，另一边接HA，中间目前看到的几个方案是：
> > 
> > 1. 淘宝不知道哪来的商家还有的DTA117D611+你的DS-AIR插件
> > 2. 中弘B18SEH+HA官方中弘插件，官方客服说不支持接入HA
> > 3. 绿米VRFKZQB19+homekit_controller，这款能接入米家，但官方客服也说不支持接入HA
> > 
> > 抠脑壳。。。
> 
> DTA117D611根据群友反馈，用这插件没有问题的。官方客服估计不了解HA，肯定不敢答应。小米都是走MIOT协议的，能接入米家的肯定能接入ha，只不过米家的设备太多了，大部分插件都没有完整支持所有的设备，可能需要自己fork下插件，简单改改来支持。


更新，终于抽出时间把HA折腾好了。。。分享一下使用经验。。。

1. 确认DTA117D611可以用，选择的是‘DTA117C611’
2. 分享一下我最终调试出来的card配置，用的simple-thermostat
```
type: custom:simple-thermostat
entity: climate.ke_ting_1
layout:
  step: row
header:
  icon: mdi:air-conditioner
control:
  hvac:
    _name: 模式
    "off":
      name: 关
    heat:
      name: 制热
    cool:
      name: 制冷
    auto:
      name: 自动
    dry:
      name: 除湿
    fan_only:
      name: 送风
  fan:
    _name: 风速
    auto:
      name: 自动风
    low:
      name: 1档
    稍弱:
      name: 2档
    medium:
      name: 3档
    稍强:
      name: 4档
    high:
      name: 5档

```
